### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by JaeDukSeo** [ildoonet/unsupervised-data-augmentation#1]
is there an implementation?

**Comment by ildoonet** [comment]
I'm starting implementations and trying to reproduce results for Image Classifications, firstly.

I push latest codes for cifar10.

**Comment by Jongchan** [comment]
@JaeDukSeo The official code (in TF) was out one week ago.
https://github.com/google-research/uda

**Comment by JaeDukSeo** [comment]
thank you!
