### ISSUE TITLE
performance of AutoAugment

### ISSUE THREAD

**Issue by vijosam** [ildoonet/unsupervised-data-augmentation#10]
I ran your code with `python train.py -c confs/wresnet28x2.yaml`, and got `top1 error=15.4%` and `best top1 error=13.4%`. I think this is corresponding to the second line of CIFAR10 results, which is 18.37. The performance in the table is much lower.

BTW, since the batchsize is really small(32), I use only one GPU card to ran the experiment.

**Comment by ildoonet** [comment]
@lydials Thanks, It has been a while after I wrote the result and fix some codes. I will update README.
