### ISSUE TITLE
Top Performance - 9.47 Error

### ISSUE THREAD

**Issue by filipafcastro** [ildoonet/unsupervised-data-augmentation#2]
Hi,

Thanks for sharing this! I would like to ask if you're obtaining the reported error of 9.47 with this version of the code, this is, by only running:

`python train.py -c confs/wresnet28x2.yaml`

**Comment by ildoonet** [comment]
Please add --unsupervised options to use UDA. And this will get you roughly 8.87 Top1 Error with this latest version of the code.

**Comment by ildoonet** [comment]
@filipafcastro I fixed issue #3, so you will get 7.28 top1 error.
