### ISSUE TITLE
Impact of cutout

### ISSUE THREAD

**Issue by filipafcastro** [ildoonet/unsupervised-data-augmentation#4]
Hi,

Have you found any explanation for the fact that using cutout is worst for performance? Actually, they use it in the original paper, right?

**Comment by ildoonet** [comment]
Yes, but in my experiment, it doesn't impact the result when I use UDA. I will rerun the experiments after fixing #5 and I will test the cutout also.

**Comment by filipafcastro** [comment]
I think it's because there's a mistake when applying the transformations. It should be something like:

Labeled Data: 
      Normalization + Default Transforms (flip, crop, padding)
Unlabeled Data: 
      "Original Examples": Normalization + Default Transforms(flip, crop, padding)
      Augmented Examples: Normalization + AutoAugment + CutOut + Default Transforms

However, the code as it is right now is applying the AutoAugment and CutOut to the labeled data, instead of doing so for the unlabeled data.

**Comment by ildoonet** [comment]
Autoaugment is also applied to augmented unlabeled data. But as you said, cutout wasn't applied to the augmented unlabeled data. I'm not sure this is needed. It will test this soon.

**Comment by ildoonet** [comment]
@filipafcastro Thanks, I tested your suggestion and the accuracy is improved : 6.26.

Much closer to the paper's result. 

Thanks!
