### ISSUE TITLE
trainloader: StratifiedSampler sampling from total_trainset?

### ISSUE THREAD

**Issue by filipafcastro** [ildoonet/unsupervised-data-augmentation#5]
Hi,

Shouldn't the dataset used in the trainloader be the trainset, instead of the total trainset? From what I understood the stratified sampler is supposed to sample from the trainset, based on its labels. This way, we're getting the indexes from the trainset, but sampling from the total train set. Or am I getting it wrong?

**Comment by ildoonet** [comment]
@filipafcastro you are right. I fixed this and get back to you after rerun experiments.

Thanks!

**Comment by ildoonet** [comment]
@filipafcastro I got slighly improved results when I fix the problem. I will commit after testing #4 . Thanks.
